### ISSUE TITLE
Excesive time compute in sparklyr 1.6 vs sparklyr 1.5.2

### ISSUE THREAD

**Issue by joscani** [sparklyr/sparklyr#2977] opened 2021-03-17 15:07 UTC
Hi. Sparklyr 1.6 is so slow compare with sparklyr 1.5.2 over the same table (cached) with tthe same resources. 
Using sparklyr over aws emr cluster 

```r
variable7 <- importancia_variables$variable[7]

tictoc::tic()
(resumen_var7 <- complete_tbl %>% 
    mutate(target_num = if_else(target == 1, 1, 0)) %>%
    mutate("{variable7}_cat" :=
             case_when(
               is.na(.data[[variable7]]) ~ "Gr1-Sin valor",
               .data[[variable7]] < 10 ~ "10-",
               .data[[variable7]] >= 0 & .data[[variable7]] <= 10 ~  "Gr3-0-10",
               .data[[variable7]] > 10 & .data[[variable7]] <= 20 ~ "Gr4-10-20",
               .data[[variable7]] > 20 & .data[[variable7]] <= 30 ~ "Gr5-20-30",
               .data[[variable7]] > 30 & .data[[variable7]] <= 40 ~ "Gr6-30-40",
               .data[[variable7]] > 40 & .data[[variable7]] <= 50 ~ "Gr7-40-50",
               .data[[variable7]] > 50  ~ "Gr8-50+")
    ) %>% 
    group_by_at(str_glue("{variable7}_cat")) %>% 
    summarise(
      filas = n(),
      ventas = sum(target_num),
      prop = sum(target_num)/n()) %>%
    # arrange(id_fecha) %>% 
    arrange_at(str_glue("{variable7}_cat")) %>% 
    as_tibble()) 
tictoc::toc()


```
With sparklyr 1.6 It takes 180 seconds and only 18 seconds with sparklyr 1.5.2, ten times faster. Any idea? 

Conf in spark  

```r 
spark_path <- "/usr/lib/spark"
Sys.setenv(SPARK_HOME = spark_path)
Sys.setenv(HIVE_CONF_DIR="/usr/lib/hive/conf")
Sys.setenv(YARN_CONF_DIR="/usr/lib/hadoop/etc/hadoop/")

conf <- sparklyr::spark_config()
conf$spark.sql.catalogImplementation <- "hive"
conf$spark.dynamicAllocation.enabled <- "false"
conf$spark.executor.instances <- 10

conf$spark.executor.cores <- 8
conf$spark.executor.memory <-  "25G"
conf$spark.driver.memory <- "2g"
conf$spark.memory.fraction <- 0.95


## init spark
spark <- spark_connect(master = "yarn",
                       version = "2.4.0",
                       config = conf,
                       app_name = "train_models")
```

**Comment by yitao-li** [comment] 2021-03-17 16:07
@joscani Nothing I can think of that could cause tihs type of slowness. Sorry.

There were dbplyr-related changes in `sparklyr` 1.6 making it comptabile with dbplyr 2.0 backend, but I don't see how that could cause performance regression.

Could you do me a favor and try `<query> %>% dbplyr::remote_query()` and see whether there is anything slow in the generated Spark SQL query?

**Comment by joscani** [comment] 2021-03-17 16:53
If I use select only  my two variables at the beginning. 

```r
resumen_var7 <- complete_tbl %>% 
    select_at(c(str_glue("{variable7}"), "target")) %>%
more_dplyrverbs

```
The query is exactly the same, and both version of sparklyr run fast. 

**sparklyr 1.5.2 Spark SQL query**
```sql
# spark 1.5.2 query
> resumen_var7  %>% dbplyr::remote_query()
<SQL> SELECT `churnpost_score_cli_riesgo_anticip_cat`, COUNT(*) AS `filas`, SUM(`target_num`) AS `ventas`, SUM(`target_num`) / COUNT(*) AS `prop`
FROM (SELECT `churnpost_score_cli_riesgo_anticip`, `target`, `target_num`, CASE
WHEN (((`churnpost_score_cli_riesgo_anticip`) IS NULL)) THEN ("Gr1-Sin valor")
WHEN (`churnpost_score_cli_riesgo_anticip` < 10.0) THEN ("Gr2-10-")
WHEN (`churnpost_score_cli_riesgo_anticip` >= 0.0 AND `churnpost_score_cli_riesgo_anticip` <= 10.0) THEN ("Gr3-0-10")
WHEN (`churnpost_score_cli_riesgo_anticip` > 10.0 AND `churnpost_score_cli_riesgo_anticip` <= 20.0) THEN ("Gr4-10-20")
WHEN (`churnpost_score_cli_riesgo_anticip` > 20.0 AND `churnpost_score_cli_riesgo_anticip` <= 30.0) THEN ("Gr5-20-30")
WHEN (`churnpost_score_cli_riesgo_anticip` > 30.0 AND `churnpost_score_cli_riesgo_anticip` <= 40.0) THEN ("Gr6-30-40")
WHEN (`churnpost_score_cli_riesgo_anticip` > 40.0 AND `churnpost_score_cli_riesgo_anticip` <= 50.0) THEN ("Gr7-40-50")
WHEN (`churnpost_score_cli_riesgo_anticip` > 50.0) THEN ("Gr8-50+")
END AS `churnpost_score_cli_riesgo_anticip_cat`
FROM (SELECT `churnpost_score_cli_riesgo_anticip`, `target`, IF(ISNULL(`target` = 1.0), NULL, IF(`target` = 1.0, 1.0, 0.0)) AS `target_num`
FROM `seg_res_sample`) `q01`) `q02`
GROUP BY `churnpost_score_cli_riesgo_anticip_cat`
ORDER BY `churnpost_score_cli_riesgo_anticip_cat`
```
**sparklyr 1.6.0 Spark SQL query** The same query

```sql 
<SQL> SELECT `churnpost_score_cli_riesgo_anticip_cat`, COUNT(*) AS `filas`, SUM(`target_num`) AS `ventas`, SUM(`target_num`) / COUNT(*) AS `prop`
FROM (SELECT `churnpost_score_cli_riesgo_anticip`, `target`, `target_num`, CASE
WHEN (((`churnpost_score_cli_riesgo_anticip`) IS NULL)) THEN ("Gr1-Sin valor")
WHEN (`churnpost_score_cli_riesgo_anticip` < 10.0) THEN ("Gr2-10-")
WHEN (`churnpost_score_cli_riesgo_anticip` >= 0.0 AND `churnpost_score_cli_riesgo_anticip` <= 10.0) THEN ("Gr3-0-10")
WHEN (`churnpost_score_cli_riesgo_anticip` > 10.0 AND `churnpost_score_cli_riesgo_anticip` <= 20.0) THEN ("Gr4-10-20")
WHEN (`churnpost_score_cli_riesgo_anticip` > 20.0 AND `churnpost_score_cli_riesgo_anticip` <= 30.0) THEN ("Gr5-20-30")
WHEN (`churnpost_score_cli_riesgo_anticip` > 30.0 AND `churnpost_score_cli_riesgo_anticip` <= 40.0) THEN ("Gr6-30-40")
WHEN (`churnpost_score_cli_riesgo_anticip` > 40.0 AND `churnpost_score_cli_riesgo_anticip` <= 50.0) THEN ("Gr7-40-50")
WHEN (`churnpost_score_cli_riesgo_anticip` > 50.0) THEN ("Gr8-50+")
END AS `churnpost_score_cli_riesgo_anticip_cat`
FROM (SELECT `churnpost_score_cli_riesgo_anticip`, `target`, IF(ISNULL(`target` = 1.0), NULL, IF(`target` = 1.0, 1.0, 0.0)) AS `target_num`
FROM `seg_res_sample`) `q01`) `q02`
GROUP BY `churnpost_score_cli_riesgo_anticip_cat`
ORDER BY `churnpost_score_cli_riesgo_anticip_cat`

```

And it's fast enough for both sparklyr version, maybe the difference is when

**Comment by joscani** [comment] 2021-03-17 16:59
In sparklyr 1.6.0 , If I comment the first select
```r
resumen_var7 <- complete_tbl %>% 
    # select_at(c(str_glue("{variable7}"), "target")) %>%
    mutate(target_num = if_else(target == 1, 1, 0)) %>%
    mutate("{variable7}_cat" :=
             case_when(
               is.na(.data[[variable7]]) ~ "Gr1-Sin valor",
               .data[[variable7]] < 10 ~ "Gr2-10-",
               .data[[variable7]] >= 0 & .data[[variable7]] <= 10 ~  "Gr3-0-10",
               .data[[variable7]] > 10 & .data[[variable7]] <= 20 ~ "Gr4-10-20",
               .data[[variable7]] > 20 & .data[[variable7]] <= 30 ~ "Gr5-20-30",
               .data[[variable7]] > 30 & .data[[variable7]] <= 40 ~ "Gr6-30-40",
               .data[[variable7]] > 40 & .data[[variable7]] <= 50 ~ "Gr7-40-50",
               .data[[variable7]] > 50  ~ "Gr8-50+")
    ) %>% 
    group_by_at(str_glue("{variable7}_cat")) %>% 
    summarise(
      filas = n(),
      ventas = sum(target_num),
      prop = sum(target_num)/n())
``` 
It takes so much time to return to prompt, even without print `resumen_var7` .

**Comment by yitao-li** [comment] 2021-03-17 17:01
OK. That's interesting... There was no change in how `sparklyr` retrieves data from Spark to R either.
Do you have any column containing Spark SQL date type in your output?

**Comment by joscani** [comment] 2021-03-17 17:03
Yes, there is a date column . Give me some time.  The EMR aws in my company is near to end time, jejej.

**Comment by joscani** [comment] 2021-03-17 17:11
Thank you  @yitao-li . sparklyr team does a fantastic job.  I'll do some tests too.

**Comment by yitao-li** [comment] 2021-03-17 18:12
@joscani Another thing to try is `<dplyr query> %>% dplyr::compute()` to evaluate the entire query and store the result in some Spark temp table. This will allow us to find out whether majority of the slowness came from query execution in Spark or not. It is possible that retrieving data from Spark to R is slow as well, but I don't see any change in how data is fetched back to R between sparklyr 1.5 and 1.6. I also recommend arrow (https://spark.rstudio.com/guides/arrow) for speeding up the collection of large dataframes from Spark to R.

**Comment by nathaneastwood** [comment] 2021-03-19 16:30
Hi @yitao-li I came here to open an issue of the same ilk and noticed that this one was already open so I am commenting here. Since upgrading, we have also noticed significant performance regressions. We have spoken previously about `sparklyr:::distinct.tbl_spark()` and so we have swapped all instances of this to using `sparklyr::sdf_distinct()` but still we have some performance issues. The problem is it is really difficult to reproduce with small data and I cannot really give you our queries/data to look at. However one thing that definitely seems to have changed performance-wise is `dplyr::compute()`. Let's say I have something like this:

```r
result <- function_that_has_a_lot_of_commands(data)
result <- dplyr::compute(result)
result
```

When I look at the Spark UI, I can see that returning `result` to the R console is recalculating everything again. I don't see why it would be doing that though when I cached the results with `dplyr::compute()`? In my particular case, the resulting data is a 41 row x 4 column table that took 77 seconds to return to the R console every time even after caching the result. If you are able to provide me with some information of what to look for them I'll be happy to look into it but we tried a lot of different things today and couldn't really narrow it down.

**Comment by joscani** [comment] 2021-03-19 16:36
@nathaneastwood  I understand your point.  Can you see your compute tables in Storage tab in sparkui?

**Comment by nathaneastwood** [comment] 2021-03-19 16:37
No we can't. That was another thing that was really odd.

**Comment by yitao-li** [comment] 2021-03-19 16:46
@nathaneastwood Same as what I suggested for @joscani previously, I think comparing Spark SQL query generated by sparklyr 1.5.2 with those generated by 1.6 may help us pin point the perf problem.

Also, I have merged the change in https://github.com/sparklyr/sparklyr/pull/2979 to the main branch of `sparklyr`, which will allow you to set `options(sparklyr.dplyr_distinct.impl = "tbl_lazy")` to ensure all `dplyr::distinct()` does is adding the word `distinct` to the Spark SQL query, so, you can try `remotes::install_github("sparklyr/sparklyr")`, `options(sparklyr.dplyr_distinct.impl = "tbl_lazy")`, and then `<your dplyr query> %>% dbplyr::remote_query() %>% print()` to see what the resulting Spark SQL query looks like.

**Comment by yitao-li** [comment] 2021-03-19 17:01
@nathaneastwood @joscani Another thing I was thinking: there was this refactoring change in https://github.com/sparklyr/sparklyr/pull/2921 that was part of `sparklyr` 1.6.

It doesn't change how Spark dataframe rows are collected back to R at all, but the refactoring has the effect of making some code less "inlined" / reducing copy-pasta.

I think this may have some JIT-related implications, as in, when all of this code was exucted for the first time or even the first few times, JVM just interprets the unoptimized byte code while possibly compiling and optimizing some of this byte code to native in the background, and maybe making some code less inlined will impact the performance of the unoptimized byte code interpretation, but it should not have much impact on how fast the optimized native code runs.

I'm by no means an expert on JVM internals, but, that's my best guess at the moment.

Do you think you can try running several unrelated Spark SQL queries first and collect results back to R, which should cause JVM to compile & optimize the abovementioned code paths into efficient native code, and then run the large query you had in question and collect result to R, and see whether the perf for evaluating this last query is any better?

**Comment by joscani** [comment] 2021-03-19 17:05
I'll try my best next week. Today is holiday in Madrid. Thanks @yitao-li

**Comment by yitao-li** [comment] 2021-03-19 17:54
@joscani @nathaneastwood Actually re: issue with `dplyr::compute()` -- I think what I missed in the middle of switching `sparklyr` to use `dbplyr` 2.0 backend API is temp views in Spark are still lazily evaluated, so, just creating a named temp view in `dplyr::compute()` is not enough, the temp view also needs to be cached. So, https://github.com/sparklyr/sparklyr/pull/2980 should fix at least part of the perf problems you both saw.

**Comment by nathaneastwood** [comment] 2021-03-19 21:21
Awesome! Thanks a lot. I'll see if I can test this out on Monday.

**Comment by joscani** [comment] 2021-03-22 07:58
Hi @yitao-li  I've made some simple test using your fix on 1.6 sparklyr. 

```r 
# read , filter and compute
tictoc::tic()
test_tbl  <-  spark %>% 
  tbl(tabla_segres) %>% 
  filter(id_fecha == 20201101) %>% 
  compute()
tictoc::toc()

# first time acces to cache table
tictoc::tic()
test_tbl
tictoc::toc()

#second time 
tictoc::tic()
test_tbl
tictoc::toc()

tally(test_tbl)
```

Read table, filter and compute takes 119.195 sec elapsed
Acces to test_tbl  first time it takes 33.822 sec elapse and roughtly the same the second time. It less than 2 million rows. 
In sparklyr 1.6 I don't see table in storage sparkui tab 
```bash 
> tally(test_tbl)
# Source: spark<?> [?? x 1]
        n
    <dbl>
1 1603411
```
With sparklyr 1.5.2, the spark job starts inmediatly and read table , filter and compute takes 39.408 sec elapsed (not 119) . 
Acces first time to cached table takes 30 sec, second time 28 sec. And I see the table in storage spark ui tab

![Captura de pantalla_2021-03-22_08-56-16](https://user-images.githubusercontent.com/1321194/111957810-ca8bb300-8aec-11eb-9c84-37ce5b26c6eb.png)

**Comment by yitao-li** [comment] 2021-03-22 23:26
@joscani Interesting. So you are saying even after re-installing `sparklyr` from master with the fix in https://github.com/sparklyr/sparklyr/pull/2980 there are still perf issues?

Also, mind sharing an example input that repro's the issue if possible? Thanks!

**Comment by joscani** [comment] 2021-03-23 09:17
@yitao-li  If I try the next code I don't see any performance issue, indeed, sparklyr 1.6.0 is much faster. I see the problem when I use hive table instead of copy_to.  I think the problem is that with sparklyr 1.6.0  `df <- df %>% compuet()` does not cache the table (I don't see in storage tabs in spark ui) , and next calls needs to compute the complete dag.  The only difference I see between 1.5.2 and 1.6.0 in emr 523 (with spark 2.4 and R 3.4.1) is that with 1.5.2 compute(df) cache the table and with 1.6.0 the table is not cached.

I use sparklyr with fix. 

```r
> packageVersion("sparklyr")
[1] ‘1.6.0’
> sparklyr:::db_save_query.spark_connection
function (con, sql, name, temporary = TRUE, ...) 
{
    create_temp_view_sql <- spark_sql_query_save(con, sql, name, 
        temporary, ...)
    DBI::dbGetQuery(con, create_temp_view_sql)
    tbl_cache_sql(con, name = name, force = TRUE)
    name
}
<environment: namespace:sparklyr>
```






This code is much faster in 1.6.0, the problem is with hive table and dplyr::compute , 
```r
library(tidyverse)
library(nycflights13)
library(sparklyr)
library(tictoc)

conf <- sparklyr::spark_config()
conf$spark.sql.catalogImplementation <- "hive"
conf$spark.dynamicAllocation.enabled <- "false"
conf$spark.executor.instances <- 5

conf$spark.executor.cores <- 5
conf$spark.executor.memory <- "8G"
conf$spark.driver.memory <- "10g"

sc <- spark_connect(master = "yarn",
                    version = "2.4.0",
                    config = conf,
                    app_name = "test-issue-spark")

df <-  flights
fligth_tbl <- sc %>% copy_to(df,"flights_spark")

tic("Total")

tic("Compute and groupby")

df_compute <- fligth_tbl %>% compute()
df_compute %>% 
  filter(arr_delay >= 1) %>% 
  group_by(dest) %>% 
  count()


df_compute

toc()

tic("second time")
df_compute
toc()

tic("third time")
df_compute
toc()
toc()

toc()



--

**Comment by joscani** [comment] 2021-03-23 16:36
Hi @yitao-li . First of all. Thank you for all efforts.  I think this code can help us. 

```r
library(sparklyr)
packageVersion("sparklyr")

library(tidyverse)
library(nycflights13)
library(tictoc)

conf <- sparklyr::spark_config()
conf$spark.sql.catalogImplementation <- "hive"
conf$spark.dynamicAllocation.enabled <- "false"
conf$spark.executor.instances <- 5

conf$spark.executor.cores <- 5
conf$spark.executor.memory <- "8G"
conf$spark.driver.memory <- "10g"

sc <- spark_connect(master = "yarn",
                    version = "2.4.0",
                    config = conf,
                    app_name = "test-issue-spark")

df <-  flights
flights_tbl <- sc %>% copy_to(df,"flights_spark", overwrite = TRUE)

flights_tbl %>% 
  spark_write_table("S_NPTB_RESI_WRK.flights")

df <- sc %>% tbl("S_NPTB_RESI_WRK.flights")

tic("Total")

tic("Compute and groupby")

df_compute <- df %>% compute()
df_compute %>% 
  filter(arr_delay >= 1) %>% 
  group_by(dest) %>% 
  count()


df_compute

toc()

tic("second time")
df_compute
toc()

tic("third time")
df_compute
toc()
toc()
```
In sparklyr 1.5.2 it takes 
```bash
> toc()
third time: 0.727 sec elapsed
> toc()
Total: 13.264 sec elapsed
```
and in sparklyr 1.6.0 
``` bash
> toc()
third time: 3.789 sec elapsed
> toc()
Total: 24.754 sec elapsed
```
In sparklyr 1.5.2 is 3 times faster to acces the cached table.

**Comment by yitao-li** [comment] 2021-03-23 17:00
@joscani Hey I don't think I was able to repro it, at least not locally:

```
remotes::install_github("sparklyr/sparklyr")
packageVersion("sparklyr")
```
```
[1] ‘1.6.1’
```

Code I ran:
```
library(sparklyr)
library(tictoc)
library(nycflights13)
library(dplyr)

sc <- spark_connect(master = "local")

fligth_tbl <- copy_to(sc, flights, name = random_string())


tic("Compute and groupby")

df_compute <- fligth_tbl %>% compute()
df_compute %>%
  filter(arr_delay >= 1) %>%
  group_by(dest) %>%
  count()

print(df_compute)

toc()

tic("second time")
print(df_compute)
toc()

tic("third time")
print(df_compute)
toc()
```

output:
```
Compute and groupby: 4.21 sec elapsed
...
second time: 0.992 sec elapsed
...
third time: 0.75 sec elapsed
```

PS: also I bumped sparklyr version to 1.6.1 but that is unrelated to the reproducibility (or lack thereof) of this issue.

**Comment by joscani** [comment] 2021-03-23 17:06
Thanks @yitao-li I think the issue is with read and compute hive table. With local dataframes and copy to spark, both , sparklyr 1.5.2 and 1.6.0 makes `compute` well and I see cache sparkdatframe in sparkui. The problem is with hive table, and I have very large (long and wide) tables.

**Comment by yitao-li** [comment] 2021-03-23 17:07
@joscani Can I replace (from your example code)

```
df_compute <- df %>% compute()
df_compute %>% 
  filter(arr_delay >= 1) %>% 
  group_by(dest) %>% 
  count()
```

with

```

df_compute <- df %>% 
  filter(arr_delay >= 1) %>% 
  group_by(dest) %>% 
  count() %>%
  compute()
```

I belive the latter is what you meant, correct? (i.e., filter, group by, count the number of rows in each group, and then cache the query result)

**Comment by yitao-li** [comment] 2021-03-23 17:13
It's still not reproducible from my side. Code I run:

```
library(sparklyr)
library(dplyr)
library(nycflights13)
library(tictoc)

print(packageVersion("sparklyr"))

conf <- sparklyr::spark_config()
conf$spark.sql.catalogImplementation <- "hive"
conf$spark.dynamicAllocation.enabled <- "false"
conf$spark.executor.instances <- 5

conf$spark.executor.cores <- 5
conf$spark.executor.memory <- "8G"
conf$spark.driver.memory <- "10g"

sc <- spark_connect(master = "local",
                    version = "2.4.0")

df <-  flights
flights_tbl <- sc %>% copy_to(df,"flights_spark", overwrite = TRUE)

flights_tbl %>%
  spark_write_table("default.flights")

df <- sc %>% tbl("default.flights")

tic("Total")

tic("Compute and groupby")

df_compute <- df %>%
  filter(arr_delay >= 1) %>%
  group_by(dest) %>%
  count() %>%
  compute()

print(df_compute)

toc()

tic("second time")
print(df_compute)
toc()

tic("third time")
print(df_compute)
toc()
```

output:

Compute and groupby: 1.948 sec elapsed
second time: 0.38 sec elapsed
third time: 0.411 sec elapsed

(I took the liberty of moving `%>% compute()` to the end of the chain of dplyr verbs, because based on your previous comment I think that was what you were actually trying to accomplish)

**Comment by joscani** [comment] 2021-03-23 17:15
Yeah that is  correct . 
but in my last code I write
```r
df <- sc %>% tbl("S_NPTB_RESI_WRK.flights")

tic("Total")

tic("Compute and groupby")

df_compute <- df %>% compute()
df_compute %>% 
  filter(arr_delay >= 1) %>% 
  group_by(dest) %>% 
  count()
``` 
where I first read the table from hive and then compute , in order to cache. That's exactly the problem, in old sparklyr version, the sparkdataframe is cached with `df_compute <- df %>% compute()`  but it is not cached in sparklyr 1.6.x . 
Sorry, I can't try  anything right now. The emr cluster is closed at this time,

**Comment by joscani** [comment] 2021-03-23 17:19
Maybe is an issue with aws emr and how sparklyr  deals with hive context?

**Comment by yitao-li** [comment] 2021-03-23 19:14
@joscani I just tried running your example on EMR (I went with emr-6.2.0 though, with Spark 3.0.1, Hive 3.1.2, and Hadoop 3.2.1). I also tried `compute()` on the source table vs. `compute()` on the dplyr query results, and neither reproduced the slowness.

**Comment by joscani** [comment] 2021-03-23 20:12
@yitao-li  thanks for your efforts. I can't change the emr version in my organization. I'll do more tests and use 1.5.2 for my daily work until I get fix the problem or the sysadmins change the emr version.
Thanks

**Comment by nathaneastwood** [comment] 2021-03-24 10:40
@yitao-li I know this is closed, and I know it is really tricky to recreate. But to add some fire to the discussion, I just ran our data extraction process which normally takes ~1.5 hours and it took over 6. FWIW, the extraction process is a bunch of SQL queries which are dependent on one another, so e.g. query 2 can't run until query 1 is complete because it depends on the results of query 1 (just being clear, not being condescending). Of course we have this set up in such a way that after each query finishes, we `dplyr::compute()` the results such that the results are cached in memory saving query 2 having to execute query 1 all over again.

This is a monthly process, hence why we are only seeing this now. It reaffirms my belief that there is something seriously wrong with `dplyr::compute()`. Before it was a case that I had a function which performs a lot of complex tasks (lots of windowed + grouped operations) and took 70 seconds to return the results to R (not collecting, just printing the first 10 rows) regardless of whether I used `dplyr::compute()` or not. But this level of regression from 1.5 to 6 hours is pretty serious.

**Comment by joscani** [comment] 2021-03-24 10:58
@nathaneastwood Maybe If you use sdf_register and tbl_cache instead compute  would be a workaround for now.

**Comment by yitao-li** [comment] 2021-03-24 12:22
@nathaneastwood OK. Can I get a sense of what's your queries entail (e.g, filter, group by, count, join, etc) and the sizes of table(s) / temp view(s) involved?

**Comment by nathaneastwood** [comment] 2021-03-24 12:30
@yitao-li I'll get back to you on this, but FWIW, this does work well it seems:

```r
compute <- function(x, name, force = TRUE) {
  out <- sparklyr::sdf_register(x = x, name = name)
  sparklyr::tbl_cache(sc = sc, name = name, force = force)
  out
}
```

**Comment by yitao-li** [comment] 2021-03-24 12:37
OK. I don't think sparklyr currently implements compute.tbl_spark yet so compute is dispatched to compute.tbl_lazy in dbplyr.
There was also the switch from dbplyr edition 1 API to edition 2, which means compute.tbl_lazy in dbplyr subsequently callable into a different set of S3 methods to perform the caching operation.

**Comment by nathaneastwood** [comment] 2021-03-24 12:46
Certainly when I use the above, I see the results in the storage tab in the Spark Master UI. I am going to run some tests on my long query now to see whether it makes a difference (massive thanks to @joscani by the way).

**Comment by nathaneastwood** [comment] 2021-03-24 13:16
Some evidence:

```
r$> system.time({
      print(x)
    })
# Source: spark<?> [?? x 4]
# I cannot show output
# … with more rows
   user  system elapsed
 26.823   0.152 103.843

r$> xCached <- dplyr::compute(x, name = "xCached")

r$> system.time({
      print(xCached)
    })
# Source: spark<xCached> [?? x 4]
# I cannot show output
# … with more rows
   user  system elapsed
  0.451   0.080   1.857
```

**Comment by yitao-li** [comment] 2021-03-24 15:48
@nathaneastwood  @joscani  I think I now know what caused it:

After switching to dbplyr API edition 2, the chain of method calls becomes:

`dplyr::compute(...)` ->
 `dbplyr:::compute.tbl_sql(...)` ->
`dbplyr:::db_compute.DBIConnection(...)` ->
`dbplyr::db_save_query.DBIConnection(...)` ->
`DBI::dbExecute(...)`

The problem is the last few steps leading to `DBI::dbExecute(...)` will only execute a single Spark SQL query (namely, the rendered query from all the dplyr verbs) and is not doing any caching.

Because this "not-caching" behavior seems to have been baked into `dbplyr` now if we were to go with compute.tbl_lazy., I think the proposed solution of creating a specialized `compute.tbl_spark()` seems the best we can do for now.

**Comment by yitao-li** [comment] 2021-03-24 15:52
Actually lemme try creating a PR from my side first (it might be tricky). I'll keep you all posted on this.

**Comment by nathaneastwood** [comment] 2021-03-24 15:59
Sure thing, happy to let the Spark expert take over ;) I'll stick to R!

**Comment by nathaneastwood** [comment] 2021-03-24 19:31
FYI, with the above method, our data extraction process ran in 1 hour 23 minutes 😃

**Comment by yitao-li** [comment] 2021-03-25 00:04
@joscani @nathaneastwood My proposed fix is in https://github.com/sparklyr/sparklyr/pull/2987

It's conceptually identical to the solution you proposed previously, while satisfying the following (where the aforementioned "trickiness" came from) :

(0) The view is both created and cached after calling `compute.tbl_spark()` (duh)
(1) It does not repeat any code within `dbplyr:::compute.tbl_sql()` inside `compute.tbl_spark()`
(2) It makes sense for both dbplyr backend API edition 1 and edition 2
(3) But then there is the "weirdness" with `NextMethod()` to watch out for (this is a corollary of (1) and (2))

Also,
(4) Revising the unit test for `dplyr::compute()` to check for way more things other than `dplyr::compute()` not throwing exception (NOTE: I did not write the original version of this unit test)

**Closed** 2021-03-25 01:33 UTC

**Comment by nathaneastwood** [comment] 2021-03-25 06:49
Thanks @yitao-li. I am on annual leave from today but I will endeavour to check this on Monday. Thanks a lot for all your hard work on this issue.

**Comment by joscani** [comment] 2021-03-25 07:09
Thanks @yitao-li  and @nathaneastwood . I'll check today or tomorrow..

**Comment by joscani** [comment] 2021-03-25 08:45
Hi @yitao-li  and @nathaneastwood .
I'm just checked, and I've found some issues.

* Read and compute table
```r
tictoc::tic()
test_tbl  <-  spark %>% 
  tbl(hive_table) %>% 
  compute()
tictoc::toc()
```
It takes **40 seconds** in sparklyr 1.5.2 , but **196 seconds** using sparklyr 1.6.1 with fix #2987 

* print the cached table
```r
tictoc::tic()
test_tbl
tictoc::toc()
```
It takes **33 seconds** in sparklyr 1.5.2 and **36 seconds** in 1.6.1.  I can see the table cached in storage sparkui tab in sparklyr 1.5.2 and in sparklyr 1.6.1. That's good

In the first check (Read table and compute) I've seen  in sparklyr 1.6.1 the job it takes too much in start spark job, (I see this in jobs tab in rstudio server) . 

Last but not least, thanks to @yitao-li and @nathaneastwood

**Comment by yitao-li** [comment] 2021-03-25 09:05
@joscani Thanks for taking a look at it so quickly.

The purpose of https://github.com/sparklyr/sparklyr/pull/2987 is to make sure with both dbplyr backend API edition 1 and 2, the post condition of calling `compute()` is a view containing some query result is created and cached in Spark.

I think time taken reading a hive table to Spark is a separate issue.

**Comment by joscani** [comment] 2021-03-25 09:12
I agree with you. A separate issue. one  problem at time. jeje.
