### ISSUE TITLE
Error in force(code): Failed while connecting to sparklyr to port (8880) for sessionid (33366): Gateway in localhost:8880 did not respond.

### ISSUE THREAD

**Issue by YassminAli00** [sparklyr/sparklyr#2295] opened 2020-03-08 21:26 UTC
I get the following error when I trying to connect to sparklyr:

Error in force(code): Failed while connecting to sparklyr to port (8880) for sessionid (82348): Gateway in localhost:8880 did not respond.
    Path: /Users/yasminali/spark/spark-2.4.4-bin-hadoop2.7/bin/spark-submit
    Parameters: --driver-memory, 2g, --class, sparklyr.Shell, '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sparklyr/java/sparklyr-2.4-2.11.jar', 8880, 82348
    Log: /var/folders/9l/ddsz2y2j6kb9b25g2319p_xm0000gn/T//Rtmp4t5xRf/file62a1099ed8e_spark.log

---- Output Log ----
Error: Could not find or load main class org.apache.spark.launcher.Main

---- Error Log ----

Traceback:

1. spark_connect(master = "local")
2. shell_connection(master = master, spark_home = spark_home, app_name = app_name, 
 .     version = version, hadoop_version = hadoop_version, shell_args = shell_args, 
 .     config = config, service = spark_config_value(config, "sparklyr.gateway.service", 
 .         FALSE), remote = spark_config_value(config, "sparklyr.gateway.remote", 
 .         spark_master_is_yarn_cluster(master, config)), extensions = extensions, 
 .     batch = NULL)
3. start_shell(master = master, spark_home = spark_home, spark_version = version, 
 .     app_name = app_name, config = config, jars = spark_config_value(config, 
 .         c("sparklyr.connect.jars", "sparklyr.jars.default"), 
 .         list()), packages = spark_config_value(config, c("sparklyr.connect.packages", 
 .         "sparklyr.defaultPackages")), extensions = extensions, 
 .     environment = environment, shell_args = shell_args, service = service, 
 .     remote = remote, batch = batch)
4. tryCatch({
 .     gatewayInfo <- spark_connect_gateway(gatewayAddress, gatewayPort, 
 .         sessionId, config = config, isStarting = TRUE)
 . }, error = function(e) {
 .     abort_shell(paste("Failed while connecting to sparklyr to port (", 
 .         gatewayPort, if (spark_master_is_yarn_cluster(master, 
 .             config)) {
 .             paste0(") and address (", gatewayAddress)
 .         }
 .         else {
 .             ""
 .         }, ") for sessionid (", sessionId, "): ", e$message, 
 .         sep = ""), spark_submit_path, shell_args, output_file, 
 .         error_file)
 . })
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. value[[3L]](cond)
8. abort_shell(paste("Failed while connecting to sparklyr to port (", 
 .     gatewayPort, if (spark_master_is_yarn_cluster(master, config)) {
 .         paste0(") and address (", gatewayAddress)
 .     } else {
 .         ""
 .     }, ") for sessionid (", sessionId, "): ", e$message, sep = ""), 
 .     spark_submit_path, shell_args, output_file, error_file)
9. withr::with_options(list(warning.length = 8000), {
 .     maxRows <- 100
 .     Sys.sleep(1)
 .     logLines <- if (!is.null(output_file) && file.exists(output_file)) {
 .         outputContent <- readLines(output_file)
 .         paste(tail(outputContent, n = maxRows), collapse = "\n")
 .     }
 .     else ""
 .     errorLines <- if (!is.null(error_file) && file.exists(error_file)) 
 .         paste(tail(readLines(error_file), n = maxRows), collapse = "\n")
 .     else ""
 .     stop(paste(message, "\n", if (!is.null(spark_submit_path)) 
 .         paste("    Path: ", spark_submit_path, "\n", sep = "")
 .     else "", if (!is.null(shell_args)) 
 .         paste("    Parameters: ", paste(shell_args, collapse = ", "), 
 .             "\n", sep = "")
 .     else "", if (!is.null(output_file)) 
 .         paste("    Log: ", output_file, "\n", sep = "")
 .     else "", "\n\n", if (!is.null(output_file)) 
 .         "---- Output Log ----\n"
 .     else "", logLines, "\n\n", if (!is.null(error_file)) 
 .         "---- Error Log ----\n"
 .     else "", errorLines, sep = ""))
 . })
10. force(code)
11. stop(paste(message, "\n", if (!is.null(spark_submit_path)) paste("    Path: ", 
  .     spark_submit_path, "\n", sep = "") else "", if (!is.null(shell_args)) paste("    Parameters: ", 
  .     paste(shell_args, collapse = ", "), "\n", sep = "") else "", 
  .     if (!is.null(output_file)) paste("    Log: ", output_file, 
  .         "\n", sep = "") else "", "\n\n", if (!is.null(output_file)) "---- Output Log ----\n" else "", 
  .     logLines, "\n\n", if (!is.null(error_file)) "---- Error Log ----\n" else "", 
  .     errorLines, sep = ""))

**Comment by yl790** [comment] 2020-03-12 19:03
I wasn't able to reproduce this issue with Spark version 2.4.4

Could you try re-installing Spark? You can do so from a R interactive shell with just the following:

```
library(sparklyr)
spark_install(version = "2.4.4")
```

**Comment by yl790** [comment] 2020-03-12 19:15
Also, try launching the spark-submit binary directly from a shell and see if it crashes with "could not load main class ..." -- based on what you posted I presume this would be how to run it directly on your system

```
/Users/yasminali/spark/spark-2.4.4-bin-hadoop2.7/bin/spark-submit \
   --driver-memory 2g \
   --class sparklyr.Shell \
   /Library/Frameworks/R.framework/Versions/3.6/Resources/library/sparklyr/java/sparklyr-2.4-2.11.jar' \
   8880 \
   82348
```
If the above doesn't work then something is most likely wrong with how the classpath of Spark was configured in your system.

**Comment by yl790** [comment] 2020-03-16 16:06
Closing this issue for now but please feel free to re-open this issue if none of the above works.

**Comment by yl790** [comment] 2020-03-16 18:17
Actually the code handling server socket opening in Sparklyr might have a bug that only shows up on some platforms -- I somehow managed to repro this on 1 out of 4 linux hosts I'm working on (and it's running a standard Debian distro). Working on resolving this now.

**Comment by yl790** [comment] 2020-03-16 19:41
^^ hmm actually for me that was because the loopback interface on that host was not up while I was trying to run everything... I don't know if you might have the same issue.
You can try running `ifconfig lo up` as root and see if that fixes everything.

**Closed by yl790** 2020-03-16 19:41 UTC
Labels: spark-2.4
