### ISSUE TITLE
Support complex DataFrame list columns to be mapped to Spark SQL array and struct respectively

### ISSUE THREAD

**Issue by schlichtanders** [sparklyr/sparklyr#1615] opened 2018-07-20 09:51 UTC
Dear sparklyr,

just stumbled upon that **sparklyr does not convert the list column of doubles to an array, nor the list column of lists to a struct column**
```
library(dplyr)
library(sparklyr)

sc <- spark_connect(master="local", version="2.1.0", config = spark_config(""))
df <- data_frame(a = list(c(11.0, 111.0), c(22.0, 222.0), c(33.0, 333.0)), s = list(list(a=5, b = "foo")))
```
The ``df`` looks like below, i.e. you see that the type information for the complex columns are properly set.
```
# A tibble: 3 x 2
  a         s         
  <list>    <list>    
1 <dbl [2]> <list [2]>
2 <dbl [2]> <list [2]>
3 <dbl [2]> <list [2]>
```
Surprisingly, sparklyr cannot handle this, but throws an IllegalArgumentException
```
sdf <- copy_to(sc, df, "df", overwrite = TRUE)
```
```
Error: java.lang.IllegalArgumentException: Invaid type list
	at sparklyr.SQLUtils$.getSQLDataType(sqlutils.scala:61)
	at sparklyr.SQLUtils$.createStructField(sqlutils.scala:66)
	at sparklyr.SQLUtils.createStructField(sqlutils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:137)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

It looks like all the needed type information is available in R so that Spark sql arrays and structs should be seamlessly constructable.

**Comment by kevinykuo** [comment] 2018-07-23 02:42
We should try to support this. Separate but related, the functionality in sparklyr.nested should also be native, but we haven't decided what the best syntax/implementation ought to be.

cc @javierluraschi could we keep nested structures/listcols in mind when re-working the serialization?

**Comment by schlichtanders** [comment] 2018-10-28 09:04
sparklyr.nested is unfortunately not what is needed here. It is really more a serialization task like @kevinykuo rightly tagged it

**I regard this as a really crucial feature.**

**Compare it with Python:** Here we can serialize even numpy arrays to org.apache.spark.ml.linalg.DenseVector directly, and python lists to hive sql-arrays, and more - everything just works.

**One Example:** Currently the only way to create example data for sparklyr machine learning is to create a bunch of columns and merge them together with ft_vector_assembler...
Try to build a column with random vectors of length `K`. It could be so simple, but currently you have to create all K dimensions as extra columns and subsequently pull them together. Which is currently probably best done using rlang's triple unquote `!!!`. A bit unfortunate

Please, think about prioritizing this issue

**Comment by kevinykuo** [comment] 2018-10-29 07:07
@javierluraschi could you comment on how this would work out with the arrow stuff? I imagine they would have the right primitives to deal with listcols in tibbles.

**Comment by javierluraschi** [comment] 2018-11-07 22:32
Currently nested data is not implemented in the R arrow bindings, but yes, once https://issues.apache.org/jira/browse/ARROW-2969 is implemented, this should work in arrow.

**Comment by schlichtanders** [comment] 2018-11-09 08:54
sounds awesome, however also sounds like this would need Spark 2.4 at least, i.e. another 2 years until this might be usable in production environments

I think it would made sense to also support this without Arrow dependency, i.e. with current spark versions

**Comment by dkincaid** [comment] 2019-08-09 19:11
Are there any workarounds that we can use for the next 2 years until this is fixed? Just bumped into it myself today. We are running Spark 2.4. Do we unnest the data frame locally, copy to Spark and then use sparklyr.nested to renest it?

**Comment by yl790** [comment] 2020-04-07 14:02
@schlichtanders Hey I started working on sparklyr recently and will be looking into this issue and hopefully come up with something better as part of sparklyr 1.3.

As an update, I noticed sparklyr (built from the master branch, and soon to be released as sparklyr 1.2) now does serialize an array of doubles into a Spark SQL array as expected.

The named list (` s = list(list(a=5, b = "foo"))`) is serialized into a json string though, but ideally should be a struct instead, correct?

i.e., with

```
df <- data_frame(a = list(c(11.0, 111.0), c(22.0, 222.0), c(33.0, 333.0)), s = list(list(a=5, b = "foo")))
sdf <- sdf_copy_to(...)
```

we now end up with `sdf` being

```
# Source: spark<df> [?? x 2]
  a        s
  <chr>    <chr>
1 [11,111] "{\"a\":[5],\"b\":[\"foo\"]}"
2 [22,222] "{\"a\":[5],\"b\":[\"foo\"]}"
3 [33,333] "{\"a\":[5],\"b\":[\"foo\"]}"
```

(so column `a` looks OK, but `s` doesn't)

and then `sdf_collect(sdf)` ends up as

```
# A tibble: 3 x 2
  a        s
  <chr>    <chr>
1 [11,111] "{\"a\":[5],\"b\":[\"foo\"]}"
2 [22,222] "{\"a\":[5],\"b\":[\"foo\"]}"
3 [33,333] "{\"a\":[5],\"b\":[\"foo\"]}"
```

and ideally column `s` should contain the original `list(a = 5, b = "foo")` instead.

**Comment by yl790** [comment] 2020-04-09 10:13
@schlichtanders @dkincaid So I managed to implement the change in https://github.com/sparklyr/sparklyr/pull/2392 that allows list columns to be imported into Spark as StructTypes. You are more than welcome to try it out with `devtools::install_github(repo = "yl790/sparklyr", ref = "struct_cols")`

There is one limitation though: all elements within a list column of the R data frame must follow exactly the same schema, or else there could be unexpected nulls or missing values when the column is imported into Spark. I think this is something that is built into Spark by design.

Let me know what you think.

**Closed** 2020-04-10 15:30 UTC
Labels: featurerequest, serialization

**Comment by dkincaid** [comment] 2020-04-13 20:30
I just got a chance to try this today and it's not working for me. When I collect() the Spark DataFrame the local data frame loses the names of the StructTypes. Here is what I mean. 
The Spark DataFrame schema is
```
> sdf_schema(result %>% select(text, sentence))
$text
$text$name
[1] "text"

$text$type
[1] "StringType"


$sentence
$sentence$name
[1] "sentence"

$sentence$type
[1] "ArrayType(StructType(StructField(annotatorType,StringType,true), StructField(begin,IntegerType,false), StructField(end,IntegerType,false), StructField(result,StringType,true), StructField(metadata,MapType(StringType,StringType,true),true), StructField(embeddings,ArrayType(FloatType,false),true)),true)"
```
note that the column `sentence` is an array of Struct's where each Struct has the fields annotatorType, begin, end, result, metadata, embeddings.
When I use `collect(result)` to get a local dataframe the local dataframe has lost the field names from the Struct:
![image](https://user-images.githubusercontent.com/175190/79158337-bf3bed80-7d9b-11ea-9c80-006b25b420f0.png)

**Comment by yl790** [comment] 2020-04-14 08:06
@dkincaid Yes you are absolutely right -- https://github.com/sparklyr/sparklyr/pull/2392 only promised to make `sdf_copy_to` sensible 😅

Meanwhile there is another more recent change to make `sdf_collect` also structure-preserving and I'm happy to announce it is also completed by now.

So now if you update sparklyr locally with `devtools::install_github("yl790/sparklyr", ref = "deserialize_struct_cols")` then the workflow you described should be fully working.

PS: all this effort was taking multiple days with 2 separate changes mainly because the latter change turned out to be more complicated than I thought, with some backward compatibility edge cases that needed to be addressed.

**Comment by dkincaid** [comment] 2020-04-14 12:30
Ok, sorry. My misunderstanding. Great news that you got the other part working too. I'll give it a try today.

**Comment by dkincaid** [comment] 2020-04-14 12:43
I just gave it a try and I'm getting the same result. The struct that is in the Spark dataframe is lost when  collecting the data frame locally. The Spark data frame I have has columns that are arrays of structs. The local data frame after `collect()` contains just a list of lists in those columns.

**Comment by yl790** [comment] 2020-04-14 13:23
@dkincaid Interesting. Maybe I'm missing something. Mind sharing a full example where sdf_collect is working as expected?

Currently my only test case for sdf_collect preserving structs is in https://github.com/sparklyr/sparklyr/blob/81691c94df60490bcd9fb2eec70522a47cae07d1/tests/testthat/test-sdf-collect.R#L27-L41 btw which just says sdf_collect will return something that is equivalent to the original tibble that was sent to Spark using sdf_copy_to, but there might be some other use case that I overlooked.

**Comment by dkincaid** [comment] 2020-04-14 13:29
I will try to pull together a simple example.

**Comment by dkincaid** [comment] 2020-04-14 18:14
Here is an example:

```
library(pins)
library(sparklyr)

jsonFile <- pin("https://gitlab.com/snippets/1966532/raw")
sc <- spark_connect(master = "local", version = "2.4.3")
sentences <- spark_read_json(sc, "sentences", jsonFile)
sdf_schema(sentences)
sentences_local <- sdf_collect(sentences)
sentences_local$sentence
```
you'll see that the `sentence` column in the Spark schema is an array of struct types. When it is collected to a local data frame the struct is lost. Hope this helps.

**Comment by yl790** [comment] 2020-04-15 16:23
@dkincaid Hey thanks so much for the example!

I finally figured out the additional changes required to support column containing array of struct types (which was the case in your example, and which was, of course, different from column containing just struct types).

You can now get a preview version of sparklyr that fully supports that use case (or struct types wrapped in nested arrays as well) with the following:

```
devtools::install_github(repo = "yl790/sparklyr", ref = "sdf_collect_be_gooder")
```
