### ISSUE TITLE
Working with datasets within the Foreach-loop with sparklyr

### ISSUE THREAD

**Issue by rcrdz** [sparklyr/sparklyr#2607] opened 2020-07-21 10:02 UTC
Hey Guys,

with the [update of sparklyr](https://blog.rstudio.com/2020/05/06/sparklyr-1-2/) you can now run the foreach loop in parallel via spark.
An example is given on the page by:
```r
library(sparklyr)
library(foreach)

sc <- spark_connect(master = "local", version = "2.4")

registerDoSpark(sc)

foreach(i = 1:3, .combine = 'c') %dopar% {
  sqrt(i)
}
```
In this case, however, only calculations are performed and no local datasets need to be accessed within the Foreach-loop. But in my case I have to work with records within the-Foreach loop.
If I now execute the Foreach-loop with spark the records are not detected and I get an error message. When I load the records with `copy_to` into the Spark environment, I cannot access them properly within the Foreach-loop. 

Is there a way to use the Foreach-loop for spark for my case, or do I have to use an alternative to the Foreach-loop?

You can see a part of my code below, but the parallelization was still executed locally with SNOW. The goal now is to translate the code so that it runs with Spark. 

```r
xtsDataTrainTransformedList <- 
      foreach(slice = 1:length(listSlices), .options.snow = opts,
              .packages = c("dplyr","data.table", "forecast"), .export = ls(envir = globalenv())) %dopar% {
                
                xtsDataTrain <- window(xtsData, 
                                       start = listSlices[[slice]]$startTrain, 
                                       end = listSlices[[slice]]$endTrain)
                
                TransformationDT <- data.table(BoxCox = FALSE,
                                               Stationarization = TRUE,
                                               Standardization = TRUE)
                
                xtsDataTrainTransformed <- applyTransformation(xtsData = xtsDataTrain,
                                                               TransformationDT = TransformationDT,
                                                               param = param)
                
                return(xtsDataTrainTransformed$xtsDataTransformed)
              }
```
Thank you already now for the Feedback!

**Comment by yl790** [comment] 2020-07-21 14:01
@rcrdz Mind attaching the actual source code invoking `foreach` and a spark dataframe or (ideally) a smaller example that reproduces the problem you ran into? I might be able to help but first I would need to understand what was the actual problem.

- I think most likely the only problem here is the `window(...)` function in R -- it is a generic function applicable to any R object that can be interpreted as a time series (e.g., you can run `window(presidents, start = 1970, end = 1973)` to see it in action). It won't be applicable to a Spark dataframe (well, not yet) because there is currently no way of specifying how to interpret a Spark dataframe as a timeseries in sparklyr. The `window` functionality might be something to consider for the upcoming sparklyr 1.4 release though -- feel free to file a feature request if you believe this type of functionality is important to have.

In essence, not everything applicable to a R dataframe or other data structure will be automatically applicable to a Spark dataframe. Sometimes you need to work around such limitations.

- I guess one potential problem you might have run into is a subtle bug being addressed in https://github.com/sparklyr/sparklyr/pull/2608 -- you can run `devtools::install_github("yl790/sparklyr", ref = "fix_do_spark_bug")` to obtain a version of sparklyr that is free from that bug

- I think another problem you'll run into within an actual Spark cluster (i.e., if your spark connection is something like `sc <- spark_connect(master = "yarn-client", ...)` instead of `sc <- spark_connect(master = "local", ...)`) is the following: if your foreach loop tries to access a R object created outside of it, e.g.:

```
obj <- <create some R object>
registerDoSpark(sc)

foreach(x = 1:10) %dopar% {
   fn(object)  # apply some function to the external object
}
```

Then you'll only get well-defined behavior if `obj` from the above is something that is serializable. Inside the foreach loop, each Spark worker will receive a snapshot of `obj` and each of them will work on their own copy of `obj` independently. This may or may not be a problem for you.

**Comment by campanell** [comment] 2020-07-24 16:53
I'm having an issue with loading a data frame object within the foreach loop.

`
#------------   Create Spark Connection   -----------------------------#
sc <- spark_connect(master = "yarn-client", 
                    config = conf,
                    spark_home = "/usr/lib/spark")

registerDoSpark(sc)

foreach (mydf = iter(df, by="row"), .combine=rbind, .packages=c('dplyr','stringdist','tibble','data.table')) %dopar% {

... do a bunch of R statements
}
`
This worked great when my test data frame(df) was just 10 records.   However, when I expanded it to 36K rows and 14 columns, my spark connection just would hang.   I need to manually disconnect.

The data frame(df) is an R data frame.

Any thoughts?

**Comment by nviraj** [comment] 2020-07-26 08:33
@campanell, A beginner myself. So this could be wrong.
Could you see if it is faster by sending bigger batches of the data frame to foreach (Say 5k rows at a time depending on the workflow)? Combining results is an expensive process made even more difficult by creating a lot of tasks by iterating over row.

**Comment by yl790** [comment] 2020-07-27 16:55
@campanell I think what @nviraj mentioned will likely work. Also, you can consider using a profiling tool such as profvis to find which part of your code is taking longer as you gradually increase the number of rows from 10 to 36k.

**Comment by campanell** [comment] 2020-07-30 13:12
@nviraj @yl790 Thank you for your suggestions.   I ended up going to spark_apply to accomplish what I needed to get done.

**Closed** 2020-07-30 13:23 UTC
