### ISSUE TITLE
across() returns unexpected results when referencing another column in dataframe

### ISSUE THREAD

**Issue by Shu-Wan** [sparklyr/sparklyr#3200] opened 2021-11-14 16:54 UTC
I recently came across an unintended case when applying `across()` in sparklyr.

```r
# In dplyr
    iris %>% 
      as_tibble %>% 
      add_column(a = 1) %>% 
      mutate(across("a", ~ .x + Sepal.Length, .names = "new_a")) %>% 
      select(Sepal.Length, a, new_a)

    ## # A tibble: 150 × 3
    ##    Sepal.Length     a new_a
    ##           <dbl> <dbl> <dbl>
    ##  1          5.1     1   6.1
    ##  2          4.9     1   5.9
    ##  3          4.7     1   5.7
    ##  4          4.6     1   5.6
    ##  5          5       1   6  
    ##  6          5.4     1   6.4
    ##  7          4.6     1   5.6
    ##  8          5       1   6  
    ##  9          4.4     1   5.4
    ## 10          4.9     1   5.9
    ## # … with 140 more rows

```

```r
# In sparklyr
# lambda function does not work as expected
    iris_tbl %>% 
      mutate(a = 1) %>% 
      mutate(across("a", ~ .x + Sepal_Length, .names = "new_a")) %>% 
      select(Sepal_Length, a, new_a)

    ## # Source: spark<?> [?? x 3]
    ##    Sepal_Length     a new_a
    ##           <dbl> <dbl> <dbl>
    ##  1          5.1     1     1
    ##  2          4.9     1     1
    ##  3          4.7     1     1
    ##  4          4.6     1     1
    ##  5          5       1     1
    ##  6          5.4     1     1
    ##  7          4.6     1     1
    ##  8          5       1     1
    ##  9          4.4     1     1
    ## 10          4.9     1     1
    ## # … with more rows
```
Therefore, I check the SQL translation and find the reason
```r
    iris_tbl %>% 
      mutate(a = 1) %>% 
      mutate(across("a", ~ .x + Sepal_Length, .names = "new_a")) %>% 
      select(Sepal_Length, a, new_a) %>% 
      dbplyr::sql_render()

    ## <SQL> SELECT `Sepal_Length`, `a`, element_at(TRANSFORM(array(`a`), (Sepal_Length, x__9c773380_33cf_4231_bfb3_71ba138d3839) -> `x__9c773380_33cf_4231_bfb3_71ba138d3839` + `Sepal_Length`), 1) AS `new_a`
    ## FROM (SELECT `Sepal_Length`, `Sepal_Width`, `Petal_Length`, `Petal_Width`, `Species`, 1.0 AS `a`
    ## FROM `iris`) `q01`
```
So the translation puts the reference column directly into the `transform` function, then it is treated as a NULL which explains the results.

This problem becomes nontrivial when the number of across columns is large. 
For example
```r
    iris_tbl %>% 
      mutate(a1 = 1, a2 = 1, ...., a100 = 1) %>% # for illustration only
      mutate(across(starts_with("a"), ~ .x + Sepal_Length, .names = "new_{.col}")) %>% 
      select(Sepal_Length, a, starts_with("new_")
```

session info
```r
    sessionInfo()

    ## R version 4.1.1 (2021-08-10)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: CentOS Linux 7 (Core)
    ## 
    ## Matrix products: default
    ## BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ##  [1] ggtext_0.1.1    sparklyr_1.7.2  forcats_0.5.1   stringr_1.4.0  
    ##  [5] dplyr_1.0.7     purrr_0.3.4     readr_2.1.0     tidyr_1.1.4    
    ##  [9] tibble_3.1.6    ggplot2_3.3.5   tidyverse_1.3.1
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_1.0.7        lubridate_1.8.0   forge_0.2.0       assertthat_0.2.1 
    ##  [5] rprojroot_2.0.2   digest_0.6.28     utf8_1.2.2        R6_2.5.1         
    ##  [9] cellranger_1.1.0  backports_1.3.0   reprex_2.0.1      evaluate_0.14    
    ## [13] httr_1.4.2        pillar_1.6.4      rlang_0.4.12      uuid_1.0-3       
    ## [17] readxl_1.3.1      rstudioapi_0.13   blob_1.2.2        car_3.0-12       
    ## [21] rmarkdown_2.11    config_0.3.1      r2d3_0.2.5        htmlwidgets_1.5.4
    ## [25] gridtext_0.1.4    munsell_0.5.0     broom_0.7.10      xfun_0.28        
    ## [29] compiler_4.1.1    modelr_0.1.8      pkgconfig_2.0.3   askpass_1.1      
    ## [33] base64enc_0.1-3   htmltools_0.5.2   Metrics_0.1.4     openssl_1.4.5    
    ## [37] tidyselect_1.1.1  fansi_0.5.0       crayon_1.4.2      tzdb_0.2.0       
    ## [41] dbplyr_2.1.1      withr_2.4.2       ggpubr_0.4.0      grid_4.1.1       
    ## [45] jsonlite_1.7.2    gtable_0.3.0      lifecycle_1.0.1   DBI_1.1.1        
    ## [49] magrittr_2.0.1    scales_1.1.1      cli_3.1.0         stringi_1.7.5    
    ## [53] carData_3.0-4     ggsignif_0.6.3    fs_1.5.0          xml2_1.3.2       
    ## [57] ellipsis_0.3.2    generics_0.1.1    vctrs_0.3.8       ggsci_2.9        
    ## [61] tools_4.1.1       glue_1.5.0        hms_1.1.1         abind_1.4-5      
    ## [65] fastmap_1.1.0     yaml_2.2.1        colorspace_2.0-2  gt_0.3.1         
    ## [69] rstatix_0.7.0     rvest_1.0.2       knitr_1.36        haven_2.4.3

```

**Comment by yitao-li** [comment] 2021-11-24 19:54
This seems to be caused by an inherent limitation of Apache Spark: specifically, the when a higher-order function such as `TRANSFORM()` is used, there is no support for referential transparency inside the lambda being applied [+].

I cannot think of have a good way to overcome this type of Apache Spark limitation at the moment. If I do think of some solution, I'll post it here.

Also, I'm not really a Spark expert TBH. Hopefully some Spark experts can chime in here. Suggestions are welcome! :slightly_smiling_face: 

[+] Hmm... I think "referential transparency" is the correct technical term for this, or at least that's what I remember from school :slightly_smiling_face:

**Comment by Shu-Wan** [comment] 2021-11-25 09:13
Thanks yitao for the reply. I get that it is probably infeasible to do it in `TRANSFORM()`.

Nevertheless, I share my workaround here, hoping it may help others face the same issue.

## my take
Basic idea:
1. State SQL statement explicitly which allows column reference. eg. `mutate(new_a = a + Sepal_Length)`
2. Using named character vector + expression evaluation to handle multiple column creations.

Sample code
```r
columns <- paste("a", 1:100, " + ", "Sepal_Length", sep = "") %>% sapply(sql)
names(columns) <- paste("new_", "a", 1:100, sep = "")
iris_tbl %>%
   mutate(!!!rlang::parse_exprs(columns))
```

Hope it helps:)

**Comment by yitao-li** [comment] 2021-12-01 16:44
@Shu-Wan On a second thought, I think the workaround you had in fact can be sufficiently generalized to support most `mutate(across(...))` use cases[*] involving formula referencing other columns in `sparklyr`, and at the moment I have a proposed fix for this limitation in https://github.com/sparklyr/sparklyr/pull/3208. So, thanks for the great suggestion!

[*]: "self-referential" use cases will be potentially confusing though, e.g., consider the 1st `mutate(across()` scenario below:

```
library(sparklyr)
library(dplyr)
library(dbplyr)

sc <- spark_connect(master = "local")

sdf <- copy_to(
  sc,
  tibble::tibble(x = seq(3), y = as.character(seq(3)), z = seq(3))
)

# Both `x` and `z` are being mutated and also referenced on the RHS of the
# formula. I don't think this type of use case is reasonably well-supported
# by `dbplyr` at the moment :(
sdf %>% mutate(across(where(is.numeric), ~ exp(x + z) * sin(.x)))

# Meanwhile other use cases that are not "self-referential" are OK, e.g.,
sdf %>% mutate(across(where(is.numeric), ~ exp(as.numeric(y)) * sin(.x)))
```

Because at the moment `dbplyr` applies mutations to `x` and `z` serially in some order rather than simulaneously, but AFAIK most people would have expected such mutations to be applied simultaneously, esp. that is what `dplyr` does to R dataframes...  the generated query and final result will not be what typical R users would expect in this case. I think the best thing to do is to disallow this type of use case for now.

**Closed** 2021-12-01 19:14 UTC
Labels: wishlist
