### ISSUE TITLE
Issues with identifying temp tables in Spark 

### ISSUE THREAD

**Issue by edgararuiz** [sparklyr/sparklyr#3429] opened 2024-03-20 21:34 UTC
Issues with identifying temp tables in Spark, possible connected to a recently updated `dbplyr` package (2.5.0): https://github.com/sparklyr/sparklyr/actions/runs/8364529848/job/22900090152

```
Error : org.apache.spark.sql.AnalysisException: Column 'test_3393229349.`*`'
does not exist. Did you mean one of the following? [test_3393229349.x,
test_3393229349.y]; line 2 pos 2; 'Project ['test_3393229349.*,
monotonically_increasing_id() AS
__row_id_5fd25889_7934_434a_9902_30acf640ef2c#385613L] +- SubqueryAlias
test_3393229349 +- View (`test_3393229349`, [x#385573,y#385574]) +- LogicalRDD
[x#385573, y#385574], false
```

**Comment by edgararuiz** [comment] 2024-03-21 15:21
Yes, it seems to be an issue with how `remote_query()` is translating in `dbplyr` 2.5.0

https://github.com/sparklyr/sparklyr/blob/main/R/sdf_wrapper.R#L13

**Comment by tschutte** [comment] 2024-03-21 16:56
I'm receiving a similar error (in Databricks) that I assume is the same root cause.

Error : org.apache.spark.sql.catalyst.ExtendedAnalysisException:
[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter
with name `my_table`.`*` cannot be resolved. Did you mean one of the
following? ['`my_table`.'col`, `my_table`.`col1`]. SQLSTATE: 42703; line 1 pos 7;

Will you be opening an issue with dbplyr, or is this something that will need to be fixed in sparklyr?

**Comment by edgararuiz** [comment] 2024-03-21 17:59
Ok, getting closer to the cause. `head()` is getting mis-translated, causing a `table.*` call, instead of a simple `*`, here is a reprex: 
``` r
library(sparklyr)
packageVersion("dbplyr")
#> [1] '2.5.0'
sc <- spark_connect("local", version = "3.3.0") 
tbl_mtcars <- copy_to(sc, mtcars)
dbplyr::remote_query(tbl_mtcars)
#> <SQL> SELECT *
#> FROM `mtcars`
dbplyr::remote_query(head(tbl_mtcars, 1))
#> <SQL> SELECT `mtcars`.`*`
#> FROM `mtcars`
#> LIMIT 1
DBI::dbGetQuery(sc, "SELECT `mtcars`.`*` FROM `mtcars` LIMIT 1")
#> Error:
#> ! org.apache.spark.sql.AnalysisException: Column 'mtcars.`*`' does not
#>   exist. Did you mean one of the following? [mtcars.am, mtcars.cyl, mtcars.hp,
#>   mtcars.mpg, mtcars.vs, mtcars.wt, mtcars.carb, mtcars.disp, mtcars.drat,
#>   mtcars.gear, mtcars.qsec]; line 1 pos 7; 'GlobalLimit 1 +- 'LocalLimit 1 +-
#>   'Project ['mtcars.*] +- SubqueryAlias mtcars +- View (`mtcars`,
#>   [mpg#14,cyl#15,disp#16,hp#17,drat#18,wt#19,qsec#20,vs#21,am#22,gear#23,carb#24])
#>   +- LogicalRDD [mpg#14, cyl#15, disp#16, hp#17, drat#18, wt#19, qsec#20,
#>   vs#21, am#22, gear#23, carb#24], false
#> 
#> Run ]8;;x-r-run:sparklyr::spark_last_error()`sparklyr::spark_last_error()`]8;; to see the full Spark error (multiple lines)
#> To use the previous style of error message set
#> `options("sparklyr.simple.errors" = TRUE)`
spark_disconnect(sc)
```

<sup>Created on 2024-03-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by edgararuiz** [comment] 2024-03-21 18:00
@tschutte - So far it's seems like this is something that I need to address in `sparklyr`, but if I find otherwise, I'll make sure to link the issues if I open one in `dbplyr`

**Comment by edgararuiz** [comment] 2024-03-21 18:21
@tschutte - It looks like the issue is affecting other packages, I just commented on the already opened issue in `dbplyr`: https://github.com/tidyverse/dbplyr/issues/1480

**Comment by tschutte** [comment] 2024-03-21 18:33
Thanks!

I am seeing the issue on other dplyr verbs as well beyond head.  Filter statements for sure were also causing it.

I've already forced my scripts to use dbplyr 2.4.0, but I can try to recreate a variety of examples if you need examples of other verbs failing.

**Comment by edgararuiz** [comment] 2024-03-21 19:13
Minimal reprex:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)
library(sparklyr, warn.conflicts = FALSE)
sc <- list()
class(sc) <- c("spark_connection", "DBIConnection")
db <- lazy_frame(x = 1, y = 2, con = sc) 
head(db, 1)
#> <SQL>
#> SELECT `df`.`*`
#> FROM `df`
#> LIMIT 1
```

<sup>Created on 2024-03-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

At this time, I'm going back to thinking that the fix will reside in `sparklyr`, but I'm still researching

**Closed** 2024-03-21 21:51 UTC

**Comment by tschutte** [comment] 2024-03-25 16:31
Hi, sorry for the late reply.  I just tested from the main branch and it seems to work great.

Thank you for the quick turnaround and looking forward to the cran release.
