### ISSUE TITLE
sparklyr integration with Hive on Hadoop 3

### ISSUE THREAD

**Issue by suraggupta** [sparklyr/sparklyr#2104] opened 2019-07-31 16:03 UTC
How do we use `sparklyr` to query tables from Hive in Hadoop 3, now that catalogs for Apache Hive and Apache Spark are separated, and Spark SQL no longer seems to work? Is this something that's being worked on?

**Comment by javierluraschi** [comment] 2019-07-31 16:43
This is not under our radar, could you share some specifics of your environment? Which Spark distribution are you using? Version of Spark and Hadoop? etc. It would be ideal if you could provide for you us to reproduce this... that said, my guess is that Spark needs to be properly configureed to use the Hive catalog, I'm not sure this is specific to `sparklyr`, is it?

For instance, have you tried retrieving data from the Hive catalog using `pyspark`? Does this work? My guess is that this wouldn't work either, which would mean the Spark configuration needs to change, if it works in Python but not in R, let us know to take a look!

**Comment by SteGerm** [comment] 2019-09-17 16:07
Hi,

Since this topic is still opened and the (broad) topic match my issue I'll add some specifics about an issue we encounter on our cluster that was juste upgraded (up to HDP 3.1.4 / Hive 3.1 / Spark 2.3.2 / SparklyR 1.0.2 / YARN).
Using the following configurations (same file used to configure pyspark sessions which are working btw) we managed to have access to Hive Metastore and as such can list DB, Tables, Tables structures, BUT we can't access to data for every new managed tables. (External tables works just fine).
ie. Querying a managed table result in success query displaying expected columns but without any values.
(same query works just fine in pyspark/spark-shell and every other mean)

Configurations/Connexion (Contains some dynamic allocation configuration but it is NOT enabled on this test):
> # Import
> library(sparklyr)
> library(dplyr)
> library(DBI)
> 
> # Connexion Spark
> Sys.setenv(SPARK_HOME= "/usr/hdp/current/spark2-client")
> Sys.setenv(YARN_CONF_DIR = "/etc/hadoop/conf")
> Sys.setenv(HADOOP_CONF_DIR = "/etc/hive/conf")
> Sys.setenv(HIVE_CONF_DIR = "/etc/hive/conf")
> .libPaths( c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib"), .libPaths()   ))
> 
> conf <- config::get(file = "/app/spark/conf/config_init_spark_latest.yaml", 
+                     config = "small_light")
> 
> conf$sparklyr.shell.files <- '/etc/hive/conf/hive-site.xml'
> conf
$spark.driver.extraClassPath
[1] "/usr/hdp/current/hive-client/conf"

$spark.driver.extraLibraryPath
[1] "/usr/hdp/current/spark2-client/python/lib/,/usr/hdp/current/spark2-client/R/lib/"

$spark.driver.maxResultSize
[1] 0

$spark.driver.memory
[1] "10g"

$spark.executor.cores
[1] 4

$spark.executor.heartbeatInterval
[1] "15s"

$spark.executor.memory
[1] "5g"

$spark.home
[1] "/usr/hdp/3.1.4.0-315/spark2"

$spark.jars
[1] "/usr/hdp/current/hive_warehouse_connector/hive-warehouse-connector-assembly-1.0.0.3.1.4.0-315.jar"

$spark.master
[1] "yarn"

$spark.rdd.compress
[1] "true"

$spark.sql.catalogImplementation
[1] "hive"

$spark.submit.deployMode
[1] "client"

$spark.submit.pyFiles
[1] "/usr/hdp/current/hive_warehouse_connector/pyspark_hwc-1.0.0.3.1.4.0-315.zip"

$sparklyr.csv.embedded
[1] "^1.*"

$sparklyr.defaultPackages
[1] ""

$`sparklyr.shell.driver-class-path`
[1] "/usr/hdp/current/hive-client/conf"

$`sparklyr.shell.driver-memory`
[1] "10g"

$spark.executor.instances
[1] 3

$spark.sql.shuffle.partitions
[1] 50

$spark.dynamicAllocation.initialExecutors
[1] 3

$spark.dynamicAllocation.maxExecutors
[1] 3

$sparklyr.shell.files
[1] "/etc/hive/conf/hive-site.xml"

attr(,"config")
[1] "small_light"
attr(,"file")
[1] "/app/spark/conf/config_init_spark_v0.9.1.yaml"
> 
> sc <- spark_connect(config = conf, app_name = "test_spark2_R_static")

Queries:
> dbGetQuery(conn = sc, statement = 'show databases')
         databaseName
1             datalab
X             <some DBs>
10            default
11 information_schema
12                sys
> 
> dbGetQuery(conn = sc, statement = 'use datalab')
> 
> dbGetQuery(conn = sc, statement = 'show tables')
   database                    tableName             isTemporary
XX  datalab                         <some tables>   FALSE
97  datalab                         test              FALSE

> tbl3 <- dbGetQuery(conn = sc, statement = 'select id, dt_depot from test limit 10')
> tbl3 %>% glimpse()
Observations: 0
Variables: 2
$ id       <chr> 
$ dt_depot <chr> 

Maybe not related issue but can give some more informations dyplr::src_tbls() doesn't work:
> src_tbls(sc)
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 0.0 failed 4 times, most recent failure: Lost task 5.3 in stage 0.0 (TID 31, <some worker node>, executor 2): java.lang.ClassNotFoundException: sparklyr.Utils$$anonfun$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:80)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1651)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1639)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1638)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1638)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1872)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1821)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1810)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2039)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2060)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2079)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2104)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
	at sparklyr.Utils$.collectColumnString(utils.scala:44)
	at sparklyr.Utils$.collectColumn(utils.scala:58)
	at sparklyr.Utils.collectColumn(utils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: sparklyr.Utils$$anonfun$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.serializer.Ja

**Comment by SteGerm** [comment] 2019-09-18 14:35
Issue comes from the use of Hive LLAP that create subdirectory within table path (base & buckets for updates).
Full resolution would be to query Hive through Hive LLAP and so use HWC_warehouse_connector jar. Currently no R implementation (beeing SparkR or SparklyR) is available to make use of this connector.

@javierluraschi: Would it be to much to ask for this feature ?

**Comment by SteGerm** [comment] 2019-09-18 14:41
We managed to find a use from SparkR (it may help with develpment):

\# sparkR --jars /usr/hdp/current/hive_warehouse_connector/hive-warehouse-connector-assembly-1.0.0.3.1.4.0-315.jar

> library(SparkRHWC)
>
> hive <- build(HiveWarehouseSession.session(spark))
>
> df <- execute(hive, "show databases")
> head(df)
database_name
1 db_lab

> df <- execute(hive, "select * from db_lab.test_int limit 2")
> head(df)
id dt_depot
1 "150001005" "20170713"
2 "150001008" "20170713"

**Comment by yitao-li** [comment] 2021-02-02 22:11
There is definitely some way to make this work with `sparklyr` (or within a `sparklyr` extension that in turn works with `sparklyr). See my comment in https://github.com/sparklyr/sparklyr/issues/2127#issuecomment-772035852

Also, I'm gonna close this one because it's a duplicate of #2127

**Closed by yitao-li** 2021-02-02 22:11 UTC
