### ISSUE TITLE
Sparklyr functionality issues with Hive and Hadoop 3

### ISSUE THREAD

**Issue by sai-ch** [sparklyr/sparklyr#2137] opened 2019-10-03 22:18 UTC
Sparklyr code functional with HDP 2.6 and hive is not functional after platform upgradation.

Current Server configuration

Hive 3.1.0.3.1.0.0-78
Spark - 2.3.2.3.1.0.0-78
Hadoop - 3.1.1.3.1.0.0-78
Sparklyr - 1.0.2

Sparklyr configuration:
```
> sc
$master
[1] "yarn-client"

$method
[1] "shell"

$app_name
[1] "sparklyr"

$config
$config$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$config$sparklyr.connect.csv.embedded
[1] "^1.*"

$config$spark.sql.catalogImplementation
[1] "hive"

$config$sparklyr.connect.cores.local
[1] 32

$config$spark.sql.shuffle.partitions.local
[1] 32

$config$spark.driver.memory
[1] "8G"

$config$spark.executor.memory
[1] "4G"

$config$spark.executor.cores
[1] "60"

$config$spark.executor.instances
[1] "50"

$config$sparklyr.shell.conf
[1] "spark.driver.extraJavaOptions=-XX:MaxHeapSize=48g"

attr(,"config")
[1] "default"
attr(,"file")
[1] "/usr/lib64/R/library/sparklyr/conf/config-template.yml"

$state
<environment: 0x8b37bf0>

$spark_home
[1] "/usr/hdp/3.1.0.0-78/spark2"

$backend
A connection with                              
description "->localhost:8881"
class       "sockconn"        
mode        "wb"              
text        "binary"          
opened      "opened"          
can read    "yes"             
can write   "yes"             

$monitoring
A connection with                              
description "->localhost:8881"
class       "sockconn"        
mode        "wb"              
text        "binary"          
opened      "opened"          
can read    "yes"             
can write   "yes"             

$gateway
A connection with                              
description "->localhost:8880"
class       "sockconn"        
mode        "rb"              
text        "binary"          
opened      "opened"          
can read    "yes"             
can write   "yes"             

$output_file
[1] "/tmp/Rtmpq8lzZz/filed6e6689cef_spark.log"

$sessionId
[1] 12345

attr(,"class")
[1] "spark_connection"       "spark_shell_connection" "DBIConnection"  
```

Tempview through HiveWarehouseSession has been used to register a table in Sparklyr by the following code.

```
library(dplyr)
library(sparklyr)
library(tidyr)

conf <- spark_config() 
conf[["sparklyr.jars.default"]] <- "/usr/hdp/current/hive_warehouse_connector/hive-warehouse-connector-assembly-1.0.0.3.1.0.0-78.jar"
conf$spark.hadoop.metastore.catalog.default <- "hive"
conf$spark.security.credentials.hiveserver2.enabled <- "false"

sc <- spark_connect(master = "yarn-client", spark_home = '/usr/hdp/current/spark2-client',config = conf)
ss <- spark_session(sc)
hive <- invoke_static(sc,"com.hortonworks.hwc.HiveWarehouseSession","session",ss)%>%invoke("build")
invoke(hive,"setDatabase","demodb")
invoke(hive,"executeQuery","select * from demodb.tbl") %>% invoke("createOrReplaceTempView","spark_temptbl")
temp_tbl <- tbl(sc,"spark_temptbl")
sdf_ncol(temp_tbl )
colnames(temp_tbl )
```
Though tables can be pulled in utilizing views, sparklyr and dplyr expected functionality is not functional as expected and spark jobs are not initializing with usage of simple dplyr code like mutate even.

Hadoop 3 integration is planned for milestone 1.1.0 as per the below link. Are there any alternative temporary approaches to solve these challenges interim before this launch.

https://github.com/rstudio/sparklyr/milestone/15

Any info on the anticipated release of sparklyr with hadoop 3 integration will be helpful for our plans.

Thanks

**Comment by yitao-li** [comment] 2021-02-02 22:08
There is definitely some way to make this work with `sparklyr` (or within a `sparklyr` extension that works with `sparklyr). See my comment in https://github.com/sparklyr/sparklyr/issues/2127#issuecomment-772035852

**Comment by yitao-li** [comment] 2021-02-02 22:09
Gonna close this one because it's a duplicate of https://github.com/sparklyr/sparklyr/issues/2127

**Closed by yitao-li** 2021-02-02 22:09 UTC
Labels: featurerequest
